version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: '1000'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - /path/to/config:~/containers/jellyfin/config
      - /path/to/cache:~/containers/jellyfin/cache
